name: Typecheck
on: [push, pull_request]
jobs:
  lint:
    name: Type checks the code
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare

      - name: Typecheck code
        run: pnpm typecheck
